### ISSUE TITLE
When adding the groovy driver, I get the following error when saving the driver.

### ISSUE THREAD

**Issue by gleep52** [edasque/hubitat#5]
No signature of method: Script1.git() is applicable for argument types: (null) values: [null] Possible solutions: wait(), wait(long), is(java.lang.Object), with(groovy.lang.Closure), run(), off() on line 12

![image](https://github.com/edasque/hubitat/assets/13360377/04cfbeae-7cb2-4b1b-b5b0-58afd84fd8bf)

**Comment by edasque** [comment]
Hah! Sorry, accidental clipboard paste - fixed in https://github.com/edasque/hubitat/commit/17c112bb580d97de55488553fcd590d9a2299a0b - please add the driver again.
